# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: "curso_spring"
      MYSQL_USER: "curso_spring"
      MYSQL_PASSWORD: "curso_spring"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      